name: deploy

on:
  push:
    branches: [ main ]

permissions:
  id-token: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: set up node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: set up chrome
        uses: browser-actions/setup-chrome@latest
      - name: build node modules
        run: |
          npm i
          CHROMIUM_BIN=$(which chrome) npm run build
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          role-session-name: samplerolesession
          aws-region: "ap-northeast-3"
      - name: s3 sync 
        run: |
          aws s3 sync ./docs s3://${{ env.BUCKET_NAME }}/docs
